spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: 950830
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect